#ifndef _SEI_H_
#define _SEI_H_

#define MAX_FN 256

typedef enum {
	SEI_BUFFERING_PERIOD = 0,
	SEI_PIC_TIMING,
	SEI_PAN_SCAN_RECT,
	SEI_FILLER_PAYLOAD,
	SEI_USER_DATA_REGISTERED_ITU_T_T35,
	SEI_USER_DATA_UNREGISTERED,
	SEI_RECOVERY_POINT,
	SEI_DEC_REF_PIC_MARKING_REPETITION,
	SEI_SPARE_PIC,
	SEI_SCENE_INFO,
	SEI_SUB_SEQ_INFO,
	SEI_SUB_SEQ_LAYER_CHARACTERISTICS,
	SEI_SUB_SEQ_CHARACTERISTICS,
	SEI_FULL_FRAME_FREEZE,
	SEI_FULL_FRAME_FREEZE_RELEASE,
	SEI_FULL_FRAME_SNAPSHOT,
	SEI_PROGRESSIVE_REFINEMENT_SEGMENT_START,
	SEI_PROGRESSIVE_REFINEMENT_SEGMENT_END,
	SEI_MOTION_CONSTRAINED_SLICE_GROUP_SET,
	SEI_FILM_GRAIN_CHARACTERISTICS,
	SEI_DEBLOCKING_FILTER_DISPLAY_PREFERENCE,
	SEI_STEREO_VIDEO_INFO,
	SEI_POST_FILTER_HINTS,
	SEI_TONE_MAPPING,

	SEI_MAX_ELEMENTS  //!< number of maximum syntax elements
}SEI_type;

int sei_payload(void *ptDecHandle, void *ptVid, int payload_type, int payload_size);

#endif
